#
include ../../makedefs

LIB = $(OPENEAAGLES_LIB_DIR)/liboeBasic.a

OBJS =  \
	$(LIB)(Action.o) \
	$(LIB)(Agent.o) \
	$(LIB)(Arbiter.o) \
	$(LIB)(Behavior.o) \
	$(LIB)(State.o)

all: ${OBJS}

clean:
	-rm -f *.o

