#
include ../../makedefs

LIB = $(OPENEAAGLES_LIB_DIR)/liboeInstruments.a

OBJS =  \
	$(LIB)(Button.o) \
	$(LIB)(PushButton.o) \
	$(LIB)(RotarySwitch.o) \
	$(LIB)(Knob.o) \
	$(LIB)(Switch.o) \
	$(LIB)(SolenoidSwitch.o) 

all: ${OBJS}

clean:
	-rm -f *.o

