#
include ../../makedefs

LIB = $(OPENEAAGLES_LIB_DIR)/liboeInstruments.a

OBJS =  \
	$(LIB)(AltitudeDial.o) \
	$(LIB)(AnalogDial.o) \
	$(LIB)(DialArcSegment.o) \
	$(LIB)(DialPointer.o) \
	$(LIB)(DialTickMarks.o) \
	$(LIB)(GMeterDial.o)

all: ${OBJS}

clean:
	-rm -f *.o

