//------------------------------------------------------------------------------
// Class: Arbiter
//------------------------------------------------------------------------------
#ifndef __Eaagles_Basic_Arbiter_H__
#define __Eaagles_Basic_Arbiter_H__

#include "Behavior.h"

namespace Eaagles {

namespace Basic { 
   class List;

class State;
class Action;

//
// Class: Arbiter
//
// Description: A meta-behavior that generates a "complex action" based on the actions generated by component behaviors
//    newUbf version is a fully functional concrete class that implements simple priority arbiting - original UBF version was abstract.
//    newUbf version allows component behaviors to return null actions
//
class Arbiter : public Behavior
{
   DECLARE_SUBCLASS(Arbiter, Behavior)

public:
   Arbiter();

   // generate action based on current state
   virtual Action* genAction(const State* const state, const LCreal dt);

protected:
   // evaluates a list of actions and creates an action
   virtual Action* genComplexAction(const Basic::List* const actionSet);

   // add new behavior to list
   void addBehavior(Behavior* const);
   Basic::List* getBehaviors() const      { return behaviors; }

   // slot functions
   bool setSlotBehaviors(Basic::PairStream* const);

private:
   Basic::List* behaviors;
};

} // End Basic namespace
} // End Eaagles namespace

#endif

