#
include ../../makedefs

LIB = $(OPENEAAGLES_LIB_DIR)/liboeinstruments.a

OBJS =  \
	$(LIB)(AnalogGauge.o) \
	$(LIB)(AoaIndexer.o) \
	$(LIB)(GaugeSlider.o) \
	$(LIB)(Tape.o) \
	$(LIB)(TickMarks.o)

all: ${OBJS}

clean:
	-rm -f *.o

