#
include ../../makedefs

LIB = $(OPENEAAGLES_LIB_DIR)/liboeinstruments.a

OBJS =  \
	$(LIB)(Eadi3DObjects.o) \
	$(LIB)(Eadi3DPage.o) \
	$(LIB)(IrisGLCompat.o)

all: ${OBJS}

clean:
	-rm -f *.o

