#
include ../../makedefs

LIB = $(OPENEAAGLES_LIB_DIR)/liboebasic.a

OBJS =  \
	$(LIB)(Exponential.o) \
	$(LIB)(Lognormal.o) \
	$(LIB)(Pareto.o) \
	$(LIB)(Uniform.o)

all: ${OBJS}

clean:
	-rm -f *.o

