#
include ../../makedefs

LIB = $(OPENEAAGLES_LIB_DIR)/liboebasic.a

OBJS =  \
	$(LIB)(Function.o) \
	$(LIB)(Functions.o) \
	$(LIB)(Table.o) \
	$(LIB)(Tables.o)

all: ${OBJS}

clean:
	-rm -f *.o

